### ISSUE TITLE
ドキュメントのビルドツールを選定する

### ISSUE THREAD

**Issue by H1rono** [H1rono/cpp-tutorial#1]
## [Docusaurus](https://docusaurus.io)

使用例: [サバイバルTypeScript](https://typescriptbook.jp)
<img width="1375" alt="typescriptbook" src="https://user-images.githubusercontent.com/54711422/233085551-727240b7-20f0-4e65-9fa5-a4fcb191be87.png">

## [MkDocs](https://www.mkdocs.org)

使用例: [ゼロから学ぶC++](https://rinatz.github.io/cpp-book/)
<img width="1344" alt="rinatz-cpp-book" src="https://user-images.githubusercontent.com/54711422/233087274-502ca08c-bdad-4c3e-b042-186d0aabdb1b.png">

## [Sphinx](https://www.sphinx-doc.org/en/master/)

使用例: [ROS2 Documentation](https://docs.ros.org/en/humble/index.html)
<img width="1375" alt="ros2-documentation" src="https://user-images.githubusercontent.com/54711422/233088184-82376443-6851-4a6a-9f65-e50061b061c8.png">

## [mdBook](https://rust-lang.github.io/mdBook/)

使用例: [The Rust Programming Language 日本語版](https://doc.rust-jp.rs/book-ja/)
<img width="1375" alt="the-rust-programming-language" src="https://user-images.githubusercontent.com/54711422/233089407-45cd5ca9-6faf-4574-90fa-2088fce0a913.png">

## [kunai](https://github.com/cpprefjp/kunai)

使用例: [cpprefjp](https://cpprefjp.github.io)
<img width="1375" alt="cpprefjp" src="https://user-images.githubusercontent.com/54711422/233091877-68c6bfe7-fe77-4da4-9ec6-c8c0c84d92c6.png">
※使えるのか少々怪しい

**Comment by H1rono** [comment]
- Docsaurus: JavaScript製、JavaScriptのみで拡張可能
- MkDocs: Python製、こちらも拡張はPythonのみ対応、テーマが色々ある
- Sphinx: Python製、MarkdownではなくRSTという言語で書く必要がある、拡張はPython
- mdBook: Rust製、任意の言語で拡張が可能
- kunai: 使えるか怪しい

**Comment by H1rono** [comment]
@n-kegra どのツールがいいとかありますか?特になければmdBookにしようかと考えています。

**Comment by n-kegra** [comment]
特にないっす
この手のツール使ったことないんで、markdownで書けるならどれでもくらいに考えてます

**Comment by H1rono** [comment]
じゃあmdBookにしようと思います
