### ISSUE TITLE
ざっくりとした章立て

### ISSUE THREAD

**Issue by H1rono** [H1rono/cpp-tutorial#4]

**Comment by H1rono** [comment]
1. チュートリアル自体の紹介
2. C++ is 何
3. 環境構築
4. Hello, world!
5. 数値の四則演算
    - 演算子の話とかあっても良さそう
6. ...

@n-kegra 最初らへんはこんな感じかなって思ってますが、どうでしょうか

**Comment by n-kegra** [comment]
よさそう
演算の前か後に型とリテラルの話とかもあっていいかも

**Comment by H1rono** [comment]
6. 文字列
7. 型、リテラル
    - int, "文字列"に加えてbool, char
    - iostream...?
9. 演算子2
    - 演算は基本的に同じ型同士のみ
    - `iostream << 文字列`とか
10. if, for, while
11. ...

とかですかね?

**Comment by n-kegra** [comment]
演算子やるなら優先順位、結合規則あたりも欲しいかも
変数の初歩的な話も欲しいですけどどこにまとめますかね？

**Comment by n-kegra** [comment]
あと確認なんですけど、画面への出力はstd::coutを使うのであってますか
std::coutを使うならiostreamとストリーム演算子はHelloWorldの時点で教えざるを得ない気が

**Comment by H1rono** [comment]
> 演算子やるなら優先順位、結合規則あたりも欲しいかも 変数の初歩的な話(宣言、初期化、代入あたり)も欲しいですけどどこにまとめますかね？

6. 文字列
7. 型、リテラル
8. 変数
9. 演算子2
    - 参照の話ができるかも...?
10. if, switch, for, while
    - gotoの話も
11. ...

**Comment by H1rono** [comment]
> あと確認なんですけど、画面への出力はstd::coutを使うのであってますか std::coutを使うならiostreamとストリーム演算子はHelloWorldの時点で教えざるを得ない気が

`std::cout`を使うつもりです。ストリーム演算子はHelloWorldの時点ではいわゆる「おまじない」で、`演算子2`の節で「ストリーム演算子」という名前を出して、演算子を独自定義できると言う話をさらに後でやるのが丸いのかなと思ってます

**Comment by n-kegra** [comment]
C++23の時代が来たらstd::printを推したいが、今はまだその時ではない...

**Comment by n-kegra** [comment]
とりあえず最初のうちに教えるべきこととしてはこのくらいで過不足無さそう

**Comment by H1rono** [comment]
> とりあえず最初のうちに教えるべきこととしてはこのくらいで過不足無さそう

じゃあいい感じに目次作ってPR出します
